const record = [
  [  // 2025.10.5
    {
      "黒川" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }  
    },
    {
      "杉浦" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "田前" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "鬼塚" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "下町" : {
        PA: 1,
        atBat: 0,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "西" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "前野" : {
        PA: 1,
        atBat: 1,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
  ],
  [  // 2025.9.14
    {
      "黒川" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 3,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 1,
        K: 0,
      }  
    },
    {
      "杉浦" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "久木田" : {
        PA: 3,
        atBat: 2,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 2,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "田前" : {
        PA: 3,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 1,
        RBI: 4,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "鬼塚" : {
        PA: 3,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 2,
        K: 0,
      }
    },
    {
      "下町" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "枝元" : {
        PA: 3,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 2,
        K: 0,
      }
    },
    {
      "比嘉" : {
        PA: 3,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 1,
      }
    },
    {
      "前野" : {
        PA: 3,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
  ],
  [  // 2025.6.22
    {
      "黒川" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 3,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }  
    },
    {
      "米田" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,
      }
    },
    {
      "久木田" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "田前" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 1,
        RBI: 2,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "西" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "鬼塚" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "下町" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 0,
        K: 1,
      }
    },
    {
      "枝元" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
  ],
  [  // 2025.3.29
    {
      "黒川" : {
        PA: 4,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 1,
        RBI: 4,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 4,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }  
    },
    {
      "杉浦" : {
        PA: 4,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "西" : {
        PA: 4,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 1,
        HR: 0,
        RBI: 1,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "鬼塚" : {
        PA: 4,
        atBat: 4,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "下町" : {
        PA: 4,
        atBat: 4,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "前野" : {
        PA: 4,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
  ],
  [  // 2025.3.9
    {
      "黒川" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 1,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }  
    },
    {
      "杉浦" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "久木田" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 0,
        K: 1,
      }
    },
    {
      "鬼塚" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "田前" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "枝元" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "比嘉" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
  ],
  [  // 2025.3.2
    {
      "黒川" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "藤田" : {
        PA: 4,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 2,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 1,
        K: 0,
      }  
    },
    {
      "杉浦" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "鬼塚" : {
        PA: 3,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 2,
        K: 0,
      }
    },
    {
      "下町" : {
        PA: 4,
        atBat: 4,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,
      }
    },
    {
      "枝元" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "比嘉" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
  ],
  [  // 2024.11.24
    {
      "黒川" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }  
    },
    {
      "杉浦" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "米田" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "鬼塚" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "枝元" : {
        PA: 1,
        atBat: 1,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "比嘉" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
  ],
  [  // 2024.07.14
    {
      "黒川" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "藤田" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }  
    },
    {
      "杉浦" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "米田" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "久木田" : {
        PA: 1,
        atBat: 0,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,
      }
    },
    {
      "鬼塚" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "下町" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "枝元" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
  ],
  [  // 2024.05.26
    {
      "黒川" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 1,
      }
    },
    {
      "藤田" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }  
    },
    {
      "杉浦" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "米田" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,
      }
    },
    {
      "久木田" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 1,
      }
    },
    {
      "鬼塚" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,
      }
    },
    {
      "下町" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
    {
      "枝元" : {
        PA: 1,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,
      }
    },
  ],
  [  // 2024.03.31
    {
      "黒川" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 1,
        BB: 0,
        K: 0,  
      }
    },
    {
      "藤田" : {
        PA: 4,
        atBat: 4,
        single: 1,
        double: 1,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,  
      }
    },
    {
      "杉浦" : {
        PA: 4,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 1,  
      }
    },
    {
      "米田" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,  
      }
    },
    {
      "久木田" : {
        PA: 3,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 2,
        BB: 1,
        K: 0,  
      }
    },
    {
      "田前" : {
        PA: 4,
        atBat: 2,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 2,
        K: 0,  
      }
    },
    {
      "鬼塚" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 2,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,  
      }
    },
    {
      "下町" : {
        PA: 3,
        atBat: 3,
        single: 2,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 2,
        BB: 0,
        K: 1,  
      }
    },
    {
      "比嘉" : {
        PA: 3,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 2,  
      }
    },
  ],
  [  // 2024.03.03
    {
      "黒川" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,  
      }
    },
    {
      "藤田" : {
        PA: 3,
        atBat: 3,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,  
      }
    },
    {
      "杉浦" : {
        PA: 3,
        atBat: 3,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,  
      }
    },
    {
      "米田" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 1,  
      }
    },
    {
      "久木田" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,  
      }
    },
    {
      "鬼塚" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 1,
        clutchHit: 1,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,  
      }
    },
    {
      "下町" : {
        PA: 2,
        atBat: 2,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 2,  
      }
    },
    {
      "枝元" : {
        PA: 2,
        atBat: 1,
        single: 0,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 1,
        K: 0,  
      }
    },
    {
      "西" : {
        PA: 2,
        atBat: 2,
        single: 1,
        double: 0,
        triple: 0,
        HR: 0,
        RBI: 0,
        clutchHit: 0,
        sucrificeBunt: 0,
        sucrificefly: 0,
        SB: 0,
        BB: 0,
        K: 0,  
      }
    },
  ],
]
